version: "3.8"

services:
    django:
        container_name: django_docker
        build:
            context: .
            dockerfile: Dockerfile
       # command: python manage.py runserver
        command: gunicorn devpro.wsgi -b 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes: 
            - .:/proyecto