# Generated by Django 3.1.7 on 2021-04-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tabla', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion_tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion_proyecto', models.CharField(blank=True, max_length=200, null=True)),
                ('financiamiento_proyecto', models.CharField(blank=True, max_length=45, null=True)),
                ('id_etapa', models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.etapa')),
                ('id_inversion', models.ForeignKey(db_column='id_inversion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.inversion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento_persona', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion_persona', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inversionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inversionista', models.CharField(blank=True, max_length=45, null=True)),
                ('empresa_inversionista', models.CharField(blank=True, max_length=45, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='inversion',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo'),
        ),
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_experto', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion_experto', models.CharField(blank=True, max_length=200, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cliente', models.CharField(blank=True, max_length=45, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.proyecto')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo')),
            ],
        ),
    ]
